### ISSUE TITLE
Error in Quickeebooks::Shared::Service::Filter#datetime_to_xml

### ISSUE THREAD

**Issue by patrickreiner** [ruckus/quickeebooks#69]
I was getting a .strftime error in datetime_to_xml when trying to filter with :before or :after because @value is nil.

I implemented this fix and it works as expected now:

module Quickeebooks
  module Shared
    module Service
      class Filter

```
    def datetime_to_xml
      start_time = @after || Time.mktime(2000, 1, 1)
      end_time = @before || Time.mktime(2020, 1, 1)
      if @field == "CreateTime"
        start_field = 'StartCreatedTMS'
        end_field = 'EndCreatedTMS'
      elsif @field == "UpdateTime"
        start_field = 'StartModifiedTMS'
        end_field = 'EndModifiedTMS'
      end
      "<#{start_field}>#{formatted_datetime(start_time)}</#{start_field}>" +
      "<#{end_field}>#{formatted_datetime(end_time)}</#{end_field}>"
    end

  end
end
```

  end
end

**Comment by ruckus** [comment]
Hi Patrick,

Thanks for the note. 

I could probably update the documentation to make this more clear. What you want to do can be done via:

filters << Quickeebooks::Windows::Service::Filter.new(:datetime, :field => 'StartCreatedTMS', :value => Time.mktime(2013, 5, 1))
filters << Quickeebooks::Windows::Service::Filter.new(:datetime, :field => 'EndCreatedTMS', :value => Time.mktime(2013, 5, 31))
s.list(filters)

The key is to specify the :field and the :value attributes. Then because you want to bound it between two dates you call it twice.

While your monkey-patch can work in some cases it has the attribute names hard-coded into the "if" checks - so its not as flexible.

Give the above a shot and let me know.

Cheers.

**Comment by patrickreiner** [comment]
Hi Ruckus,

I will go ahead and change my implementation and re-post if I have any issues. Yes, I think updating the documentation would be great if you get around to doing it.

I was following these examples when I initially encountered the error:

# find all customers created after 2/15/2011

datetime = Time.mktime(2011, 2, 15)
Quickeebooks::Shared::Service::Filter.new(:datetime, :field => 'CreateTime', :after => datetime)

# find all customers created before 3/28/2011

datetime = Time.mktime(2011, 2, 28)
Quickeebooks::Shared::Service::Filter.new(:datetime, :field => 'CreateTime', :before => datetime)

and so I monkey-patched it to have the above code work as expected.

Thank you very much for creating this code by the way, I find it super useful and am grateful to be able to use it!

**Comment by ruckus** [comment]
Ah I see!

Yes, the docs were outdated. I just updated them with basically the same info I gave you.

Thanks for the heads up! I hate incorrect documentation.
